//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaldaGameWFA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaldaGameWFA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аак
        ///аба
        ///аво
        ///ага
        ///аге
        ///ада
        ///азу
        ///азы
        ///аил
        ///айн
        ///аир
        ///айю
        ///ако
        ///акр
        ///акт
        ///аку
        ///ала
        ///але
        ///амт
        ///ант
        ///апе
        ///ара
        ///арк
        ///аск
        ///асс
        ///аул
        ///аут
        ///ахи
        ///аэд
        ///аян
        ///аят
        ///бай
        ///бак
        ///бал
        ///бан
        ///бар
        ///бас
        ///бат
        ///бег
        ///бей
        ///бек
        ///бел
        ///бес
        ///биг
        ///бид
        ///био
        ///бир
        ///бит
        ///бич
        ///боа
        ///боб
        ///бог
        ///бод
        ///бой
        ///бок
        ///бом
        ///бон
        ///боп
        ///бор
        ///бот
        ///бра
        ///бри
        ///бру
        ///брэ
        ///буж
        ///буи
        ///буй
        ///бук
        ///бум
        ///бур
        ///бут
        ///буш
        ///бык
        ///быр
        ///быт
        ///бэр
        ///вад
        ///важ
        ///ваи
        ///вал
        ///ван
        ///вар
        ///век
        ///вес
        ///вех
        ///веш
        ///виг
        ///вид
        ///вис
        ///воз
        ///вой
        ///вок
        ///вол
        ///вор
        ///вут
        ///выя
        ///вяз
        ///гад
        ///газ
        ///гай
        ///гак
        ///гал
        ///га [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaldaDictionary {
            get {
                return ResourceManager.GetString("BaldaDictionary", resourceCulture);
            }
        }
    }
}
